name: fbla_member_app
description: A member app for Future Business Leaders of America (FBLA)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  http: ^1.2.2
  html: ^0.15.4
  url_launcher: ^6.3.1
  table_calendar: ^3.1.2
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/fbla_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/fbla_logo.png"